version: 'cypress-docker-v1'
services:
    cypress-chrome:
      image: cypress/included:13.6.0
      command: "-b chrome"
      working_dir: /cypress_testing 
      volumes:
        - ./:/cypress_testing 

    cypress-firefox:
      image: cypress/included:13.6.0
      command: "-b firefox"
      working_dir: /cypress_testing 
      volumes:
        - ./:/cypress_testing
    
    cypress-electron:
      image: cypress/included:13.6.0
      working_dir: /cypress_testing 
      volumes:
        - ./:/cypress_testing 

